### ISSUE TITLE
Crash with node-ffi 2.0

### ISSUE THREAD

**Issue by rosen-vladimirov** [node-ffi/node-ffi#238] opened 2015-09-09 09:25 UTC
Hi, 

I have two different problems (one on MAC and one on Windows), but as I believe both have the same root cause, I'll add them here. I can separate them in case you think they are not connected:

## Using node-ffi 2.0 on MAC
I'm trying a very simple script, that leads to core dump on Mac OS:
```JavaScript
var ffi = require("ffi");
global.gc();
console.log("END");
```
When I call it with: 
```
iojs --expose_gc --nouse_idle_notification --trace_gc test.js
```
I receive core dump.

I've set DEBUG environment variable and you can find the output [in this gist](https://gist.github.com/rosen-vladimirov/18eec3bc00c709295ea0) I've also placed there the core dump file in case it can help.
I'm using iojs 3.3.0 and latest versions of ffi and ref:
```
 iojs
> process.versions
{ http_parser: '2.5.0',
  node: '3.3.0',
  v8: '4.4.63.30',
  uv: '1.7.3',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  modules: '45',
  openssl: '1.0.2d' }
```

Please note the crash is on the line `global.gc()`.

## Using node-ffi on Windows
On Windows the issues is more complicated, but it is also related to garbage collection. In our code we are trying to call methods from CoreFoundation.dll, which is part of iTunes installation. When we have some short calls and our process terminates, everything is working fine. But when our process starts working for some long time, we receive Assertion error: 
```
Assertion failed: (obj_data) != (nullptr), file src\node_buffer.cc,  line 150
```
It looks like the garbage collector had collected something that we are trying to use later.
So we've tried to simplify the reproduction case and we've found that we fail only when trying to create ForeignFunction for specific method of the dll. Please note - we are not using them in the test script, just using ffi.

You can find the repro script and the output when DEBUG=* in [this gist](https://gist.github.com/rosen-vladimirov/7f44089c8c35960b7990)

I believe the problem is not in the dll itself, as the same code is working fine with node 0.10, node 0.12, iojs 2.x

Could you take a look at these issues? I believe the problem is in iojs's garbage collection, but I'm not able to reproduce the issue on Windows with all calls, only some of them lead to crash when garbage collection is working.

Your help is really appreciated. I'm looking forward to hearing from you.

**Comment by rosen-vladimirov** [comment] 2015-09-09 09:34
btw I believe it is related to [this issue](https://github.com/nodejs/node/issues/2484), so I'm using iojs 3.2.0 or later, but the problem still exists :(

**Comment by unbornchikken** [comment] 2015-09-09 14:23
Does it occur on Linux?

**Comment by unbornchikken** [comment] 2015-09-09 14:39
Lemme answer my own question, it doesn't. I don't have MAC but I can try to reproduce this on Windows. But I can't promise that I can do this before weekend.

**Comment by unbornchikken** [comment] 2015-09-09 14:45
Are you sure about that ref@1.1 is installed? It can happen that you have a ref 1.0 right inside in node_modules, and ffi will pick that up instead of ref@>1.1.

**Comment by rosen-vladimirov** [comment] 2015-09-09 15:06
Hi @unbornchikken 
I was unable to reproduce it on Linux, but I have not tested a lot of ForeignFunction calls there. 
I've just double-checked the versions on Mac and Windows - ref is 1.1.0
I'm ready to help you with anything you need, maybe I should drop some lines in the iojs/nodejs issue that you've opened before?

**Comment by unbornchikken** [comment] 2015-09-09 19:48
Lemme try this first at my side.

**Comment by rosen-vladimirov** [comment] 2015-09-09 20:42
Ok, thank you for your efforts. I'll be waiting for your reply and as I've said - I'm ready to test any fix, patch, idea or whatever you think about :smile_cat:

**Comment by unbornchikken** [comment] 2015-09-10 07:47
So, I've investigated it. Let's split this into two issues, because that OSX one is different than this Windows one.

I believe that OSX issue is related about that node issue that you [referenced before](https://github.com/nodejs/node/issues/2484). I think that commit that intended to fix alignment issue of new Buffer doesn't work on properly on the OSX build of io.js. Windows and Linux is not affected. Please open up an other issue including your repro case and I'll assistance you further there, because I need your help for investigation since I don't own a OSX .

The Windows one is interesting. I've tested our latest ffi with many-many DLL-s referenced, including OpenCL from various vendors, and everything works properly. However if I reference that iTunes DLL then I get a crash. I think iTunes is doing some library initialization logic that somehow corrupts io.js 3+'s memory. I can see in the debugger that the error is about GC thinks that memory is occupied but instead it gets nullified somehow. We can open up a node issue referencing this one with the repro case. What do you think?

**Comment by rosen-vladimirov** [comment] 2015-09-10 09:39
Hi @unbornchikken,
Thank you very much for the investigation. Your plan sounds good, I'll open another issue here for OSX problem and I'll open another one in node repository for the Windows case.

**Comment by unbornchikken** [comment] 2015-09-10 09:41
Eventually we're gonna go to node issues with OSX case too, but first we should investigate it further, because I think it is ref related issue instead of an ffi one.

**Comment by unbornchikken** [comment] 2015-09-10 10:17
I think it's more related to exported function pointer alignment instead of library initialization error that I thought before.

**Comment by TooTallNate** [comment] 2015-09-18 21:36
This is fixed with Node.js v4.1.

**Closed by TooTallNate** 2015-09-18 21:36 UTC
